- name: Check if vagrant is installed
  shell: |
    vagrant --version
  ignore_errors: yes
  register: vagrant_check

- name: Install vagrant
  become: true
  apt: 
    deb: "{{ vagrant_deb }}"
  when: vagrant_check.rc != 0

- name: Check if virtualbox is installed
  shell: |
    vboxmanage --version
  ignore_errors: yes
  register: virtualbox_check

- name: Install virtualbox
  become: true
  apt: 
    deb: "{{ virtualbox_deb }}"
  when: virtualbox_check.rc != 0
  
- name: Check if vagrant plugin vguest is installed
  shell: |
    vagrant plugin list | grep vagrant-vbguest
  ignore_errors: yes
  register: vagrant_plugin_check

- name: Install vagrant-vguest
  shell: |
    vagrant plugin install vagrant-vbguest
  when: vagrant_plugin_check.rc != 0

- name: Check if ovftool is installed
  shell: |
    ovftool --version
  ignore_errors: yes
  register: ovftool_check

- name: Download ovftool
  get_url:
    url: "{{ ovftool_bundle }}"
    dest: /tmp/ovftool.bundle
    force: yes
  when: ovftool_check.rc !=0

- name: Install ovftool
  become: true
  shell: |
    set timeout -1
    spawn bash /tmp/ovftool.bundle
    match_max 100000
    expect "*Press Enter to proceed."
    send -- "\r"
    expect "*--More--*"
    send -- "q"
    expect "*Do you agree?*"
    send -- "yes\r"
    expect "* Press Enter to begin\r
    installation or Ctrl-C to cancel."
    send -- "\r"
    expect eof
    catch wait result
    exit [lindex $result 3]
  args:
    executable: /usr/bin/expect
  when: ovftool_check.rc !=0

- name: Install apache2
  become: true
  apt: name={{item}} state=present
  with_items:
    - apache2
    - apache2-doc
    - apache2-utils

- name: Install python tools
  become: true
  pip: name={{item}} state=present
  with_items:
    - virtualenv
    - ansi2html

