---
- hosts: packer
  roles:
    - replace-apt-source
    - for-jenkins-connection
    - install-fundamental-tools
    - install-package-for-build
    - install-vagrant-stack
    - install-packer-build-stack
    - install-ansible
